In [1]:
import numpy as np

In [2]:
listas = [1, 2, 3, 4, 5]

In [3]:
arr = np.array(listas)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
mano_listai = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
matrica = np.array(mano_listai)

In [6]:
matrica

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.linspace(0,20,16)

array([ 0.        ,  1.33333333,  2.66666667,  4.        ,  5.33333333,
        6.66666667,  8.        ,  9.33333333, 10.66666667, 12.        ,
       13.33333333, 14.66666667, 16.        , 17.33333333, 18.66666667,
       20.        ])

In [11]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(10)

array([0.42811662, 0.26986249, 0.42286251, 0.2898974 , 0.18927576,
       0.67862802, 0.4120058 , 0.06696773, 0.36895649, 0.75023831])

In [13]:
np.random.rand(5,5)

array([[0.79033421, 0.80683525, 0.71626403, 0.14774974, 0.08933607],
       [0.29836689, 0.54395889, 0.98022586, 0.74955995, 0.72916377],
       [0.14390015, 0.74474088, 0.12163936, 0.12769342, 0.52647415],
       [0.92985524, 0.45456   , 0.57470273, 0.6939307 , 0.28184792],
       [0.27965239, 0.8331813 , 0.49167941, 0.21611632, 0.66881359]])

In [14]:
np.random.randn(3,3)

array([[ 0.04268717,  0.16908912, -0.10558678],
       [-0.68552513,  0.4742698 , -0.73347375],
       [-0.11784074,  0.019784  , -0.07137813]])

In [15]:
np.random.randint(100, 200, 20)

array([131, 127, 139, 141, 102, 186, 153, 106, 171, 158, 114, 104, 139,
       126, 162, 171, 163, 144, 173, 177])

In [16]:
my_array = np.random.randint(0, 100, 64)

In [17]:
my_array

array([23, 68, 92,  2, 34,  3, 16, 81, 91, 16, 71, 12, 17,  9, 81, 20, 12,
       88, 96, 94, 75, 23, 49,  9, 84, 60, 30, 93, 18, 40, 89, 38, 53, 89,
       37, 37, 34, 74, 60, 50,  1, 98, 10,  0, 31, 69, 60, 50, 23, 46, 43,
       13, 76, 67, 31,  2, 39, 37, 29, 46, 58, 41, 36, 24])

In [18]:
reshaped_array = my_array.reshape(8,8)

In [19]:
reshaped_array

array([[23, 68, 92,  2, 34,  3, 16, 81],
       [91, 16, 71, 12, 17,  9, 81, 20],
       [12, 88, 96, 94, 75, 23, 49,  9],
       [84, 60, 30, 93, 18, 40, 89, 38],
       [53, 89, 37, 37, 34, 74, 60, 50],
       [ 1, 98, 10,  0, 31, 69, 60, 50],
       [23, 46, 43, 13, 76, 67, 31,  2],
       [39, 37, 29, 46, 58, 41, 36, 24]])

In [20]:
my_array.min()

0

In [21]:
my_array.max()

98

In [22]:
my_array.argmax()

41

In [23]:
my_array.argmin()

43

In [24]:
reshaped_array.shape

(8, 8)

In [25]:
reshaped_array.dtype

dtype('int32')

In [26]:
sample_array = np.arange(1,10)

In [27]:
sample_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
sample_array[5]

6

In [29]:
sample_array[2:8]

array([3, 4, 5, 6, 7, 8])

In [30]:
sample_array[6:]

array([7, 8, 9])

In [31]:
sample_array[4:8] = 50

In [32]:
sample_array

array([ 1,  2,  3,  4, 50, 50, 50, 50,  9])

In [33]:
sample = np.random.randint(1, 10, 25)

In [34]:
sample_matrix = sample.reshape(5,5)

In [35]:
sample_matrix

array([[7, 7, 9, 6, 3],
       [5, 3, 1, 5, 2],
       [4, 2, 9, 3, 4],
       [7, 3, 4, 2, 5],
       [8, 8, 1, 5, 4]])

In [36]:
sample_matrix[2,2] 

9

In [37]:
sample_matrix[1:4, 1:4]

array([[3, 1, 5],
       [2, 9, 3],
       [3, 4, 2]])

In [38]:
sample_matrix[3:,:]

array([[7, 3, 4, 2, 5],
       [8, 8, 1, 5, 4]])

In [39]:
sample_matrix[:, 0:2]

array([[7, 7],
       [5, 3],
       [4, 2],
       [7, 3],
       [8, 8]])

In [40]:
masyvas = np.arange(1,21)

In [41]:
masyvas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
bool_masyvas = masyvas > 9

In [43]:
bool_masyvas

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [44]:
masyvas[bool_masyvas]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
masyvas[masyvas>9]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
pvz = np.random.randint(1, 21, 20)

In [47]:
pvz

array([10, 10, 12,  6,  2,  3,  3, 15,  6,  4,  7, 11, 19, 12,  2,  5,  4,
       15, 19, 14])

In [48]:
pvz_ispjova = pvz[5:15]

In [49]:
pvz_ispjova

array([ 3,  3, 15,  6,  4,  7, 11, 19, 12,  2])

In [50]:
pvz_ispjova[:] = 99

In [51]:
pvz_ispjova

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [52]:
pvz

array([10, 10, 12,  6,  2, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,  5,  4,
       15, 19, 14])

In [53]:
pvz_copy = pvz.copy()

In [54]:
pvz_copy

array([10, 10, 12,  6,  2, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,  5,  4,
       15, 19, 14])

In [55]:
pvz_copy == pvz

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [56]:
pvz_copy_ispjova = pvz_copy[5:15]
pvz_copy_ispjova[:] = 100

In [57]:
pvz_copy_ispjova

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [58]:
pvz

array([10, 10, 12,  6,  2, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,  5,  4,
       15, 19, 14])

In [59]:
pvz_copy

array([ 10,  10,  12,   6,   2, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100,   5,   4,  15,  19,  14])

In [60]:
vektorius = np.arange(1,11)

In [61]:
vektorius

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
vektorius + vektorius

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [63]:
vektorius * vektorius

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [64]:
vektorius / vektorius

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
vektorius / 0

array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [66]:
vektorius + 1000

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010])

In [67]:
vektorius ** 3


array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [68]:
np.sin(vektorius)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [69]:
np.log(vektorius)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])