In [1]:
import numpy as np

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
1.sukurti vektoriu su skaiciais nuo 1 iki 9

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
2.sukurti vektoriu su 10 nuliu


In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
3.vektorius iš 10 vienetų

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
4.vektorius iš 10 ketvertų.

In [8]:
np.fours(10)

<class 'AttributeError'>: module 'numpy' has no attribute 'fours'

In [9]:
np.four(10)

<class 'AttributeError'>: module 'numpy' has no attribute 'four'

In [10]:
np.ones(10) * 4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [ ]:
5. vektorius iš lyginių skaičių nuo 0 iki 100

In [11]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [12]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
6.matrica iš 25 narių, pradedant 1, baigiant 25. 
Priskirkite ją kintamąjam.

In [13]:
arr = np.arange(1,26)

In [14]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [15]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
7.Is matricos skaicius 12

In [16]:
arr[2,1]

<class 'IndexError'>: too many indices for array: array is 1-dimensional, but 2 were indexed

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [18]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [23]:
arr[2,1]

<class 'IndexError'>: too many indices for array: array is 1-dimensional, but 2 were indexed

In [24]:
arr = np.arange(1,26).reshape(5,5)

In [25]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
arr[2,1]

12

In [27]:
arr[1,2]

8

In [28]:
arr[0,2]

3

In [ ]:
8. Iš matricos ištraukti paskutinę eilutę.

In [29]:
arr[-1]

array([21, 22, 23, 24, 25])

In [ ]:
9. Iš matricos ištraukite submatricą

In [30]:
arr[:3, :3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
10. Iš matricos ištraukite submatricą

In [31]:
arr[1:4, 1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [ ]:
11. Iš matricos ištraukti submatricą

In [32]:
arr[3:, :3]

array([[16, 17, 18],
       [21, 22, 23]])

In [ ]:
vektorius iš 20 atsitiktinių reikšmių,
nuo 0 iki 1. 
Priskirkite kintamąjam.

In [33]:
np.random.rand(20)

array([0.88872489, 0.48736399, 0.32711148, 0.10087594, 0.69709712,
       0.06233049, 0.77412523, 0.13827646, 0.88519116, 0.79427485,
       0.64871273, 0.37931922, 0.88866843, 0.75748578, 0.33838539,
       0.55577755, 0.13006733, 0.07574982, 0.26449007, 0.29942434])

In [35]:
visokie = np.random.rand(20)

In [36]:
visokie

array([0.05608311, 0.50449205, 0.62032238, 0.23122912, 0.96842768,
       0.60278018, 0.2565733 , 0.48471836, 0.39129015, 0.98503741,
       0.48947622, 0.18305357, 0.05956726, 0.07093192, 0.12150153,
       0.31791677, 0.17623602, 0.81119709, 0.76948479, 0.61248587])

In [ ]:
13. didžiausia reikšme masyve ir jos indeksą.

In [37]:
visokie.max()

0.9850374119856333

In [38]:
visokie.argmax()

9

In [ ]:
14. mažiausia reikšme ir jos indeksą

In [39]:
visokie.min()

0.056083109383815555

In [40]:
visokie.argmin()

0

In [ ]:
15. Koks matricos duomenų tipas

In [41]:
visokie.dtype

dtype('float64')

In [ ]:
16. Sukurti vektorių iš integer reikšmių nuo 1 iki 100. 
Priskirkite kintamąjam. 
Iš jo ištraukite visus skaičius, didesnius už 90

In [42]:
kitokie = np.arange(1,101)

In [43]:
kitokie

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [44]:
kitokie[kitokie > 90]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
17. Ištraukite iš vektoriaus visus skaičiaus 7 kartotinius

In [45]:
visokie[visokie % 7 == 0]

array([], dtype=float64)

In [46]:
kitokie[kitokie % 7 == 0]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [ ]:
18.Sukurti matrica, kas 0,025 didejantys skaiciai.
iki 1.025.

In [49]:
np.linspace(0.025,1.025).reshape(5,10)

array([[0.025     , 0.04540816, 0.06581633, 0.08622449, 0.10663265,
        0.12704082, 0.14744898, 0.16785714, 0.18826531, 0.20867347],
       [0.22908163, 0.2494898 , 0.26989796, 0.29030612, 0.31071429,
        0.33112245, 0.35153061, 0.37193878, 0.39234694, 0.4127551 ],
       [0.43316327, 0.45357143, 0.47397959, 0.49438776, 0.51479592,
        0.53520408, 0.55561224, 0.57602041, 0.59642857, 0.61683673],
       [0.6372449 , 0.65765306, 0.67806122, 0.69846939, 0.71887755,
        0.73928571, 0.75969388, 0.78010204, 0.8005102 , 0.82091837],
       [0.84132653, 0.86173469, 0.88214286, 0.90255102, 0.92295918,
        0.94336735, 0.96377551, 0.98418367, 1.00459184, 1.025     ]])

In [ ]:
19. sukurkite tokią matricą 
(sveiki sk. nuo 2 iki 1000 iš kurių traukiasi sveika šaknis):

In [50]:
nauja = np.arange(2,1001)

In [51]:
saknis = nauja[(nauja ** 0.5) % 1 ==0].reshape(6,5)

In [52]:
saknis

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

In [ ]:
20.papildoma.
Sukurkite vektorių iš sveikų sk. nuo 1 iki 100. 
Priskirkite kintamąjam.

In [53]:
sveiki = np.arange(1,101)

In [ ]:
Sukurkite Python funkciją, kuri tikrina 
ar parametruose įvestas sk. yra pirminis. 
Jeigu pirminis, grąžina True, jei ne, False.

In [54]:
def pirminis(skaicius):
    for i in range(2, skaicius):
        if skaicius % i == 0:
            return False
    return True

In [ ]:
vektorizuoti taip : 
nauja_funkcija = np.vectorize(jūsų_funkcija)

In [55]:
vektorizacija = np.vectorize(pirminis)

In [56]:
sveiki[vektorizacija(sveiki)]

array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
       59, 61, 67, 71, 73, 79, 83, 89, 97])